### ISSUE TITLE
Some keyboard shortcuts working sporadically or not at all

### ISSUE THREAD

**Issue by JGLAHE** [husonlab/splitstree6#11]
In SplitsTreeCE_windows-x64_6_2_1-beta, the rotate left/right keyboard shortcuts don't seem to start working for ~20 seconds after opening (on my system, I've repeated this 3 times with the same result). The increase font size doesn't seem to be working at all, despite the decrease font size working fine (although only from the `-` key near the backspace; the `-` on the number pad doesn't do anything.
Cheers

**Comment by husonlab** [comment]
Does clicking on the tab associated with the pane in which you want to rotate stuff make any difference? I will take a look at the short-cut key issue

**Comment by lccra** [comment]
Hi @husonlab , you will have to just take my word on this but @JGLAHE is my old account: I've lost access to it following the death of the iphone linked to that account. If you believe me, you can close this issue, cheers
