### ISSUE TITLE
Export image option greyed-out

### ISSUE THREAD

**Issue by JGLAHE** [husonlab/splitstree6#13]
I'm pretty sure the export to .svg was working previously? Is there anything special I have to setup once I have the neighbour net on screen?

**Comment by niWdooG** [comment]
I came across the same issue. I've solved this by installing the 6.1.9.beta version:
https://software-ab.cs.uni-tuebingen.de/download/splitstree6/SplitsTreeCE_windows-x64_6_1_9-beta.exe
