### ISSUE TITLE
Previous versions of executables?

### ISSUE THREAD

**Issue by JGLAHE** [husonlab/splitstree6#14]
Is it possible to keep previous versions of the executables up at https://software-ab.cs.uni-tuebingen.de/download/splitstree6/welcome.html?

Cheers

**Comment by husonlab** [comment]
They are there, you just need to change the version number of the URL for a current installer to access an older version.

Here is a list of version numbers currently hosted:

0_1_0-alpha
0_1_1-alpha
0_1_2-alpha
0_1_3-alpha
0_1_4-alpha
0_1_5-alpha
0_1_6-alpha
0_1_7-alpha
0_1_8-alpha
0_2_0-alpha
0_2_1-alpha
0_2_2-alpha
0_2_3-alpha
0_2_4-alpha
0_2_5-alpha
0_2_6-alpha
0_3_0-alpha
0_3_1-alpha
0_3_3-alpha
0_3_4-alpha
0_3_5-alpha
0_3_6-alpha
0_3_7-alpha
0_3_8-alpha
0_3_9-alpha
0_4_0-alpha
0_4_1-alpha
0_4_2-alpha
0_4_3-alpha
0_4_4-alpha
6_0_34-beta
6_0_35-beta
6_1_0-beta
6_1_10-beta
6_1_11-beta
6_1_12-beta
6_1_13-beta
6_1_14-beta
6_1_15-beta
6_1_16-beta
6_1_1-beta
6_1_2-beta
6_1_3-beta
6_1_5-beta
6_1_6-beta
6_1_7-beta
6_1_8-beta
6_1_9-beta
6_2_0-beta
6_2_1-beta
