### ISSUE TITLE
Configure max threads/logical processors available to SplitsTree

### ISSUE THREAD

**Issue by JGLAHE** [husonlab/splitstree6#15]
Like with the memory, it would be good if the user could nominate the maximum number of logical processors available to SplitsTree in the installer dialogue. Even better if this could be configured within the running application, although I've no idea how difficult that would be to achieve... Cheers

**Comment by husonlab** [comment]
If you launch the program from the command line, then you can pass `-t number-of-threads` to specify how many threads any one algorithm may use during computations. However, you run two algorithms in parallel, then both will get the given number of threads. Also, Java itself uses multiple threads for different tasks and these are not limited by the option. However, the latest version of Java supports "virtual threads" and this may allow the program to specify the maximum number of actual threads to use. I will look into this.

**Comment by lccra** [comment]
Sorry if this is slightly off-topic (in a closed issue), but does calling SplitsTree from the command line in Linux assume (and require) access to a GUI, or is it purely a cli? Cheers
