### ISSUE TITLE
How can I batch modify the colors of edges in a .nex file? Thanks!

### ISSUE THREAD

**Issue by hwhw97** [husonlab/splitstree6#17]
How can I batch modify the colors of edges in a .nex file? Thanks!

**Comment by husonlab** [comment]
That is not possible at present, I have added it to my to-do list.

**Comment by davidjamesbryant** [comment]
I bet this is possible with ChatGPT + grep!

Sorry about my lack of response to the last few emails. I’ve been busy arranging the sale of Mums house, which has become complicated as we’ve discovered it is a ‘leaky’ house which basically can only be sold to builders or developers.

It was great to hear that you had a good time canoe camping. I remember now how difficult it was to traverse a lake with a side wind and how some days we just had to hug the shore. Also how it was sometimes quite difficult to find the outlet of a lake!

I’d love to see some photos. Which route did you do?

I’ve attached a photo from the last time I was in Quebec city… as you can see it has been a while!


-Dave.



From: husonlab ***@***.***>
Date: Thursday, 5 September 2024 at 4:39 AM
To: husonlab/splitstree6 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [husonlab/splitstree6] How can I batch modify the colors of edges in a .nex file? Thanks! (Issue #17)

That is not possible at present, I have added it to my to-do list.
