### ISSUE TITLE
No Export > Image available

### ISSUE THREAD

**Issue by cornejoem** [husonlab/splitstree6#2]
Hello und schönen Tag!

As I have not been able to install the current version of SplitsTree4 on my M1 MBP, macOS 13.3 I ran SplitsTree CE, but have been unable to export any image files in high resolution (print > PDF works). The preferences are also not available.
I would appreciate if you could let me know if I am missing something.
<img width="1150" alt="Screenshot 2023-04-10 at 12 53 23 PM" src="https://user-images.githubusercontent.com/50105887/230951780-3dedcba9-2882-43df-bbd5-d45c66d4ea5f.png">
<img width="890" alt="Screenshot 2023-04-10 at 12 53 48 PM" src="https://user-images.githubusercontent.com/50105887/230951782-3ada3989-9893-4fc0-8243-008bb764237b.png">

**Comment by husonlab** [comment]
Thank you for your message. I have added an File->Export->Image... menu item and also an export image button (top left tool bar). These export to gif, png and tif. Export to PDF or SVG would be nice, but I haven't been able to implement that yet. This new feature is implemented in 6.0.24-beta, which I am currently uploading.
SplitsTree4 should work even on an M1 Mac, I will look into this.
