### ISSUE TITLE
Nexus File do not open: Expected 1720 taxon name, found 1723

### ISSUE THREAD

**Issue by StephanieRodrigues** [husonlab/splitstree6#22]
Hi All,
I am trying to run splitsTree for a gene. I have my alignment but once I tried to open I got this message:
Failed:Line 1725: expected 1720 taxon names, found: 1723
Open file failed: jloda.util.IOExceptionWithLineNumber: Line 1725: expected 1720 taxon names, found: 1723.

I checked my entire alignment, there is no extra taxon name. I removed any weird character from the file that could potentially cause that but I still find this error. As git does not allow me to upload a nexus, I am attaching a text file with my sequences. 
[hlgC_1720.txt](https://github.com/user-attachments/files/15825364/hlgC_1720.txt)

Thanks!

**Comment by husonlab** [comment]
I just loaded your alignment into SplitsTree. The sequence starting on line 3436 has a different length than the previous ones. If you give SplitsTree a FastA file as input then it will assume that all sequences are the same length...

**Comment by StephanieRodrigues** [comment]
Hi,
Thanks for the reply!
