### ISSUE TITLE
moving split parallelograms

### ISSUE THREAD

**Issue by rwittler** [husonlab/splitstree6#26]
In Splitstree 4, you can move around the edges of a split. This sometimes helps to "sort" the network or also to recognize some three-dimensional structure. I often use this feature when I explain the concept of splits to other people. Seeing the parallelograms moving often results in an a-ha! 
In Splitstree 6, this is not possible, right?

**Comment by husonlab** [comment]
This is possible: see the section on the Split-network tab in the user manual.

https://github.com/husonlab/splitstree6/blob/main/doc/user-manual.md#split-network-tab￼
splitstree6/doc/user-manual.md at main · husonlab/splitstree6
github.com

**Comment by rwittler** [comment]
Ah, I see. You have to use the rotate-buttons, not grab a node and move it using the mouse. Thanks for the hint!
