### ISSUE TITLE
404

### ISSUE THREAD

**Issue by liamxg** [husonlab/splitstree6#32]
Dear @dhuson,

please see below:

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/7236bbd7-6acf-4a6c-ade0-799797800878">

**Comment by lccra** [comment]
full URL?

**Comment by AnupamGautam** [comment]
You can download it from here [link](https://software-ab.cs.uni-tuebingen.de/download/splitstree6/welcome.html)
