### ISSUE TITLE
How to detect the recombination points?

### ISSUE THREAD

**Issue by liamxg** [husonlab/splitstree6#35]
Dear @husonlab,

Could I know to to detect the recombination points?

Thanks.

Best,
Liam

**Comment by husonlab** [comment]
If by "recombination points" you mean breakpoints along a sequence between different recombined parts, then SplitsTree does not provide a method for detecting these.

**Comment by husonlab** [comment]
The phi test is available in the SplitsTree app
To use it, right click on the working characters node in the side bar - the phi test it at the bottom of the list of applicable algorithms
