### ISSUE TITLE
Autumn Algorithm benchmarked in STCE?

### ISSUE THREAD

**Issue by JGLAHE** [husonlab/splitstree6#5]
Hi,

I wanted to try running the Autumn Algorithm on two max-likelihood input trees; they have slightly differnt topologies, but exactly the same 60 terminals, and both are unrooted (though the correct root is known). I've been running this for around 30 hours so far, and the memory usage seems to be a stable ~12G of 24G allocated. I skimmed through the 2018 TCBB paper, but I just wanted to check if current implimentation is known to be stable/always converges?

Cheers

**Comment by husonlab** [comment]
You need to make sure that both trees are rooted correctly, as a discrepancy in rooting with generate many additional reticulations and that will cause the algorithm to run for a very long time In general, the problem of finding a rooted network that contains both trees and has a minimum number of reticulations id NP-hardTo help the algorithm, make sure the two trees are rooted correctly and contract any edges that have low supportSent from Daniel Huson's phoneOn 30 Jun 2023, at 14:24, JGLAHE ***@***.***> wrote:﻿
Hi,
I wanted to try running the Autumn Algorithm on two max-likelihood input trees; they have slightly differnt topologies, but exactly the same 121 terminals, and both are unrooted (though the correct root is known). I've been running this for around 30 hours so far, and the memory usage seems to be a stable ~12G of 24G allocated. I skimmed through the 2018 TCBB paper, but I just wanted to check if current implimentation is known to be stable/always converges?
Cheers

**Comment by JGLAHE** [comment]
Cheers - thanks for that!
